--- @class ActionWrapper
--- @field AdjustedActionId number
--- @field RecastTimeElapsed number
--- @field RealRecastTimeElapsed number
--- @field RecastTime number
--- @field RealRecastTime number
--- @field SpellCooldown number
--- @field RealSpellCooldown number
