--- @class EnvManagerWrapper
--- @field DayTimeSeconds number
--- @field ActiveTransitionTime number
--- @field CurrentTransitionTime number
--- @field IsInGame number
--- @field TransitionTime number
