--- @class FlagWrapper
--- @field TerritoryId number
--- @field MapId number
--- @field XFloat number
--- @field YFloat number
--- @field Vector2 Vector2
--- @field Vector3 Vector3
--- @field SetFlagMapMarker fun(territoryId: number, mapId: number, x: number, y: number): nil
--- @field SetFlagMapMarker fun(territoryId: number, x: number, y: number): nil
