--- @class OccultCrescentStateWrapper
--- @field CurrentKnowledge number
--- @field NeededKnowledge number
--- @field NeededJobExperience number
--- @field Silver number
--- @field Gold number
--- @field CurrentSupportJob number
--- @field KnowledgeLevelSync number
